---
### Pre-Installation
- name: "Download latest Debian package of step-cli"
  ansible.builtin.get_url:
    url: "https://dl.smallstep.com/cli/docs-cli-install/latest/step-cli_amd64.deb"
    dest: "{{ step_cli_tmp_dir }}/step-cli_amd64.deb"
    mode: '0600'
  environment: "{{ proxy_env }}"
  check_mode: false
  tags:
    - install

### Installation
- name: "Be sure step-cli is installed at its latest version (APT based)"
  ansible.builtin.apt:
    deb: "{{ step_cli_tmp_dir }}/{{ step_cli_apt_packages }}"
    state: "{{ step_cli_apt_state }}"
  become: true
  when: ansible_pkg_mgr == 'apt'
  tags:
    - install

### Configuration
# - name: "Copy proxy configuration to APT (if needed)"
#   ansible.builtin.template:
#     src: apt.conf.d/90proxy.j2
#     dest: /etc/apt/apt.conf.d/90proxy
#     mode: '0644'
#   when: ansible_pkg_mgr == 'apt'
#   become: true
#   tags:
#     - conf
