---
### Pre-Installation

### Installation
- name: "Be sure step-cli is at its latest version (APT based)"
  ansible.builtin.apt:
    deb: "{{ stepcli_apt_packages }}"
    state: "{{ stepcli_apt_state }}"
  become: true
  when: ansible_pkg_mgr == 'apt'
  tags:
    - install

### Configuration
# - name: "Copy proxy configuration to APT (if needed)"
#   ansible.builtin.template:
#     src: apt.conf.d/90proxy.j2
#     dest: /etc/apt/apt.conf.d/90proxy
#     mode: '0644'
#   when: ansible_pkg_mgr == 'apt'
#   become: true
#   tags:
#     - conf
