---
###########################
### Facts set

- name: "Show architecture"
  debug:
    msg: "Arch : {{ ansible_architecture }}"
  tags:
    - install

- name: "Set step_cli_arch variable from facts"
  set_fact:
    step_cli_arch: "{{ step_cli_arch_match[ansible_architecture] }}"
  tags:
    - install

###########################
### Pre-Installation
- name: "Download latest Debian package of step-cli"
  ansible.builtin.get_url:
    url: "{{ step_cli_url_deb }}"
    dest: "{{ step_cli_tmp_dir }}/{{ step_cli_deb }}"
    mode: '0600'
  environment: "{{ proxy_env }}"
  check_mode: false
  tags:
    - install

###########################
### Installation
- name: "Be sure step-cli is installed at its latest version (APT based)"
  ansible.builtin.apt:
    deb: "{{ step_cli_tmp_dir }}/{{ step_cli_deb }}"
    state: "{{ step_cli_apt_state }}"
  become: true
  when: ansible_pkg_mgr == 'apt'
  tags:
    - install

###########################
### Configuration
# - name: "Copy proxy configuration to APT (if needed)"
#   ansible.builtin.template:
#     src: apt.conf.d/90proxy.j2
#     dest: /etc/apt/apt.conf.d/90proxy
#     mode: '0644'
#   when: ansible_pkg_mgr == 'apt'
#   become: true
#   tags:
#     - conf
